spring:
  application:
    name: spring-boot-readnovel
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/Read}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 369996143369-fut88d8pplces4bf4k3ekgmib491i7d1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: mlanhem28@gmail.com
    password: tdxdniynteyvvojr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  signer-key: "yYwQxlBVCRKhVM7gtymmF4AikjlcEom+DcyVjkvY4HFHcGAaiolb7IT+kDE6ucgFcyc2LflaNJfJS3PIoSZmYQ=="
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

encryption:
  aes:
    password: eL8/8q4qcxBL+hLn1d/YwQ==
    salt: c1185cc206e23482

payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:WXBCTBAJ}
    secretKey: ${SECRET_KEY:OCRHYF0O3K3IRW2T7A66ZNCT1PFRNOAO}
    returnUrl: ${RETURN_URL:http://localhost:8080/payment/vn-pay-callback}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}