spring:
  application:
    name: spring-boot-readnovel
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${ID_GOOGLE}
            client-secret: ${SECRET_GOOGLE}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL:mlanhem28@gmail.com}
    password: ${PASSWORD_MAIL:tdxdniynteyvvojr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  signer-key: ${SIGNER_KEY_JWT}
  valid-duration: ${ACCESS_TIME_JWT}
  refreshable-duration: ${REFRESH_TIME_JWT}
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:WXBCTBAJ}
    secretKey: ${SECRET_KEY:OCRHYF0O3K3IRW2T7A66ZNCT1PFRNOAO}
    returnUrl: ${RETURN_URL:http://localhost:3000/payment/vnpay-return}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://569898377162755:X820dhqTuh4BR-6Fc9-tnts6RF0@dxpyuj1mm}

encryption:
  aes:
    password: eL8/8q4qcxBL+hLn1d/YwQ==
    salt: c1185cc206e23482

url:
  frontend: ${URL_FRONTEND:http://localhost:3000}
  admin-frontend: ${URL_FRONTEND:http://localhost:3001}
  app-frontend: ${URL_APP_FRONTEND:http://localhost:19006}